import { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";
import Footer from "@/components/Footer";
import { SavedProvider } from "@/context/SavedContext";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className="min-h-full flex flex-col">

       <ThemeProvider>
        <SavedProvider>
        <Navbar/>
        <main className="min-h-screen">
          {children}
          <Toaster position="top-right" richColors offset={80}/>
          </main>
        </SavedProvider>
        </ThemeProvider>
        <Footer/>

      </body>
    </html>
  );
}
